name: Build

on: workflow_dispatch

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:  # !!! FIXME: figure out an efficient way to get SDL2 on the Windows/Mac bots.
        - { name: Linux,   os: ubuntu-20.04, flags: -GNinja, build_type: "Release" }
        - { name: Windows, os: windows-latest, build_type: "Release" }
        - { name: MacOS,   os: macos-latest, build_type: "Release" }
    steps:
    - name: Setup Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build
    - name: Get PhysicsFS sources
      uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.platform.build_type }} ${{ matrix.platform.flags }}
    - name: Build
      run: cmake --build build --config ${{ matrix.platform.build_type }}
    - uses: actions/upload-artifact@v3
      with:
        path: build
